services:
  medichaser:
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: app
    env_file:
      - .env
    volumes:
      - medichaser_data:/app/data
    ports:
      - 7681:7681
    platform: "linux/amd64"
volumes:
  medichaser_data: